### ISSUE TITLE
Titra seems not to be running within a Docker Swarm

### ISSUE THREAD

**Issue by NK0D1NG** [kromitgmbh/titra#106]
Hello,
I wanted to try out Titra, but I have problems get it up and running within my Docker Swarm Cluster.
I am using Traefik v2 as a reverse proxy. I get redirected to the signin page, but the page is empty or is not looking correctly:
![grafik](https://user-images.githubusercontent.com/88783636/157710749-8f02b594-01a6-458d-a885-9300e3c40f77.png)

I think there is a problem loading the css/js files? Should I use localhost as the ROOT_URL? The deployment instructions are not that precise..

```

titra_app.1.yfsdkt8qf9cc@v220210169548138574    | [ERROR: [ostrio:flow-router-extra] [route.wait] Promise not resolved @ Thu Mar 10 2022 16:30:45 GMT+0000 (Coordinated Universal Time)] {
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "browserInfo": {
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "userId": null,
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "url": "https://titra.mydomain.de/",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "resolution": "3440x1440"
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   },
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "stack": {}
titra_app.1.yfsdkt8qf9cc@v220210169548138574    | }
titra_app.1.yfsdkt8qf9cc@v220210169548138574    | [ERROR: TypeError: $(...).popover is not a function @ Thu Mar 10 2022 16:30:45 GMT+0000 (Coordinated Universal Time)] {
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "file": "https://titra.mydomain.de/7db791e51d98db0c3681323b36f53d484eb0660a.js?meteor_js_resource=true",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "onLine": 206,
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   "browserInfo": {
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "userId": null,
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "url": "https://titra.mydomain.de/signIn",
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |     "resolution": "3440x1440"
titra_app.1.yfsdkt8qf9cc@v220210169548138574    |   }
titra_app.1.yfsdkt8qf9cc@v220210169548138574    | }

```

The database service is running and the logs don't show anything error related.

This is my Docker-Compose File:
```
version: "3.5"
services:
  app:
    image: kromit/titra
    environment:
      - ROOT_URL=https://titra.mydomain.de?directConnect=true
      - MONGO_URL=mongodb://mongodb/titra?directConnection=true
      - PORT=3000
    networks:
      - titra
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - traefik.http.routers.titra-http.rule=Host(`titra.mydomain.de`)
        - traefik.http.routers.titra-http.entrypoints=http
        - traefik.http.routers.titra-http.middlewares=https-redirect
        - "traefik.http.routers.titra-https.rule=Host(`titra.mydomain.de`)"
        - "traefik.http.routers.titra-https.tls=true"
        - "traefik.http.routers.titra-https.tls.certresolver=netcup"
        - "traefik.http.routers.titra-https.entrypoints=https"
        - "traefik.http.services.titra.loadbalancer.server.port=3000"
    ports:
      - 4000:3000

  mongodb:
    image: mongo:4.4
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
    volumes:
      - titra:/data/db
    networks:
      - titra

volumes:
  titra:
    driver_opts:
      type: "nfs"
      o: "addr=mynfs,nolock,soft,rw"
      device: ":/srv/storage/titra"

networks:
  traefik-public:
    external: true
  titra:
    driver: overlay
```
Any hints what the problem could be?
