### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by LukeSetzer** [kromitgmbh/titra#137]
Hello, we installed Titra last week, and tried to create users, then we got the Error [notifications.auth_error_method].

![download](https://user-images.githubusercontent.com/107842109/174557624-f050071a-4a6c-48b9-ad0c-846b4d49d4c1.png)

How can we fix this?

Kind Regards
Luke Setzer

**Comment by faburem** [comment]
I cannot reproduce this issue, can you please provide a bit more information on the steps taken to get this error?
Also the error stack of the browser/server console would be interesting to see!

Thanks,
Fabian

**Comment by LukeSetzer** [comment]
I installed Titra with docker-compose and used this command 

curl -L https://github.com/faburem/titra/raw/master/docker-compose.yml | ROOT_URL=http://localhost:3000 MAIL_URL=smtp://x:y@x.net:25 docker-compose -f - up 

x and y to cover details

here are two error screens
![Screenshot_1](https://user-images.githubusercontent.com/107842109/175256122-caf46fbc-6ab5-4c87-90d1-b9d5495d5baa.png)
![Screenshot_2](https://user-images.githubusercontent.com/107842109/175256128-1ef5f373-5a5d-4b54-a31b-09900d7d7538.png)

**Comment by faburem** [comment]
based on the error log I would assume your login has expired. Can you try to refresh the page without cache? It should take you to the login page I assume and then it should work.

Best,
Fabian

**Comment by noraj** [comment]
I encounter the same issue also with the docker compose.

It's not only the user creation form it is all Admin features under `http://localhost:3000/admin`.

For example trying to change general settings:

![image](https://user-images.githubusercontent.com/16578570/177130717-8a4f722f-e854-49e1-bad1-3afdb4d05585.png)

It's not an authentication error the token is still active for 1month and log out and log in back don't change the behavior.

![image](https://user-images.githubusercontent.com/16578570/177131283-86d55a4f-8b1e-4255-944d-5ab1b276ba98.png)

**Comment by Chron-O-John** [comment]
Hey, I just want to tune in and say, I have the same problem.
Installed using your docker-compose with docker 20.10.7.
Created one account and went to admin-page.
In the user-menu (within admin) I see, that admin is not ticked, maybe thats a clue?

**Comment by faburem** [comment]
I tried to reproduce this again with a fresh docker-compose instance but everything was working fine.
We really want to fix this but we need to identify the root cause - any additional information is highly appreciated!

**Comment by noraj** [comment]
I used this docker compose:

```
version: '3'
services:
  titra:
    image: kromit/titra
    container_name: titra_app
    depends_on:
      - mongodb
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongodb/titra?directConnection=true
      - PORT=3000
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
  mongodb:
    image: mongo:5.0
    container_name: titra_db
    restart: always
    environment:
      - MONGO_DB:titra
    volumes:
      - titra_mongodb_volume:/data/db
volumes:
  titra_mongodb_volume:
```

I created a user (1st user created should be admin). Then I tried to modify some settings and save but it doesn't save anything.

```
➜ docker --version                   
Docker version 20.10.17, build 100c70180f
➜ docker-compose --version                    
Docker Compose version 2.6.1
```
