### ISSUE TITLE
Details view shows only UTC hours

### ISSUE THREAD

**Issue by ekezet** [kromitgmbh/titra#184]
Hi!

In the latest release which is **0.95.2** with start time tracking enabled, the UI is showing UTC hours instead of the browser's timezone (in my case Europe/Budapest)  in details view. When I try to edit the recorded entry it shows the correct time, and when I export it for example in csv format the hours are in UTC instead of the local timezone. I attach some screenshots, and post down the docker-compose.yml for reproducing the issue. Thanks for any help!

```yaml
version: '3'
services:
  titra:
    image: kromit/titra:0.95.2
    container_name: titra_app
    depends_on:
      - mongodb
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongodb/titra?directConnection=true
      - PORT=3000
    ports:
      - "3000:3000"
    restart: always
  mongodb:
    image: mongo:5.0
    container_name: titra_db
    restart: always
    environment:
      - MONGO_DB:titra
    volumes:
      - titra_db_volume:/data/db
volumes:
  titra_db_volume:
```

![Screenshot from 2023-09-13 12-14-19](https://github.com/kromitgmbh/titra/assets/46503938/52d78ff4-9547-4095-874a-b39a35bc9c6e)
![Screenshot from 2023-09-13 12-14-29](https://github.com/kromitgmbh/titra/assets/46503938/5b6b392c-79fc-488d-ba78-ba0dccbbc9e8)
